version: '3.9'

services:
  plantuml:
    container_name: PlantUML
    image: plantuml/plantuml-server:latest
    ports:
      - 8080:8080
    volumes:
      - /data/plantuml:/tmp/jetty:rw
    environment:
      - TZ=Asia/Kuching
    hostname: plantuml
    mem_limit: 2g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    user: 1026:100
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080